---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development
script:
  - make test

before_install:
  - gem update bundler

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
  allow_failures:
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.0"

notifications:
  email: false

deploy:
  provider: puppetforge
  user: "HEPPuppet"
  password:
    secure: "cF7HLnEO05rYFNukshMcw00tFudutpBqP2PF25ypbru1q+qmg/uNJp09k61wOaPYHwk/ZkpzDByGelJSPRoA04cEa/j+CshkrxfOwTzRLgEhy2FZUoBhHCDxMeQ5evG+GbzIu62Tpl9vuvxQBdIO072uF6DWEn6SjoqJQohifRk="
  on:
    tags: true
    rvm: 2.4.0
