---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development
script:
  - "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"

before_install:
  - gem update bundler

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"

notifications:
  email: false
